import type { ToolCategoryId, ToolDefinition } from '@/types/tools';

export const TOOL_CATEGORIES: { id: ToolCategoryId; title: string }[] = [
  { id: 'image', title: 'Image Tools' },
  { id: 'pdf', title: 'PDF Tools' },
  { id: 'archive', title: 'ZIP Tools' },
  { id: 'qr', title: 'QR Tools' },
  { id: 'storage', title: 'Storage Tools' },
  { id: 'browser', title: 'Files' },
];

/** Single source of truth for every home-screen utility card. */
export const TOOLS: ToolDefinition[] = [
  {
    id: 'image-compress',
    title: 'Compress Images',
    description: 'Shrink photo file size while keeping visual quality',
    icon: 'minimize-2',
    category: 'image',
    route: '/tools/image-compress',
  },
  {
    id: 'image-resize',
    title: 'Resize Images',
    description: 'Scale images to exact dimensions or a percentage',
    icon: 'maximize-2',
    category: 'image',
    route: '/tools/image-resize',
  },
  {
    id: 'image-convert',
    title: 'Convert Images',
    description: 'Switch between JPEG, PNG and WEBP formats',
    icon: 'repeat',
    category: 'image',
    route: '/tools/image-convert',
  },
  {
    id: 'image-rotate-crop',
    title: 'Rotate & Crop',
    description: 'Rotate in 90° steps or crop to a centered square',
    icon: 'crop',
    category: 'image',
    route: '/tools/image-rotate-crop',
  },
  {
    id: 'images-to-pdf',
    title: 'Images to PDF',
    description: 'Combine one or more photos into a single PDF',
    icon: 'image',
    category: 'pdf',
    route: '/tools/images-to-pdf',
  },
  {
    id: 'pdf-merge',
    title: 'Merge PDF',
    description: 'Combine and reorder multiple PDFs into one file',
    icon: 'copy',
    category: 'pdf',
    route: '/tools/pdf-merge',
  },
  {
    id: 'pdf-split',
    title: 'Split PDF',
    description: 'Extract page ranges into separate PDF files',
    icon: 'scissors',
    category: 'pdf',
    route: '/tools/pdf-split',
  },
  {
    id: 'pdf-compress',
    title: 'Compress PDF',
    description: 'Optimize a PDF to reduce its file size',
    icon: 'file-minus',
    category: 'pdf',
    route: '/tools/pdf-compress',
  },
  {
    id: 'zip-extractor',
    title: 'ZIP Extractor',
    description: 'Browse and extract the contents of a ZIP archive',
    icon: 'folder-minus',
    category: 'archive',
    route: '/tools/zip-extract',
  },
  {
    id: 'zip-creator',
    title: 'ZIP Creator',
    description: 'Bundle files together into a new ZIP archive',
    icon: 'folder-plus',
    category: 'archive',
    route: '/tools/zip-create',
  },
  {
    id: 'qr-scanner',
    title: 'QR Code Scanner',
    description: 'Scan any QR code using your camera',
    icon: 'camera',
    category: 'qr',
    route: '/tools/qr-scan',
  },
  {
    id: 'qr-generator',
    title: 'QR Code Generator',
    description: 'Create codes for text, links, Wi-Fi and more',
    icon: 'grid',
    category: 'qr',
    route: '/tools/qr-generate',
  },
  {
    id: 'file-cleaner',
    title: 'File Cleaner',
    description: 'Clear temporary files and empty folders',
    icon: 'trash-2',
    category: 'storage',
    route: '/tools/file-cleaner',
  },
  {
    id: 'downloads-manager',
    title: 'Downloads Manager',
    description: 'Review files you have recently imported or saved',
    icon: 'download',
    category: 'storage',
    route: '/tools/downloads-manager',
  },
  {
    id: 'large-files',
    title: 'Large Files Finder',
    description: 'Find the files taking up the most space',
    icon: 'hard-drive',
    category: 'storage',
    route: '/tools/large-files',
  },
  {
    id: 'duplicate-finder',
    title: 'Duplicate File Finder',
    description: 'Detect duplicate files wasting storage space',
    icon: 'copy',
    category: 'storage',
    route: '/tools/duplicate-finder',
  },
  {
    id: 'storage-analyzer',
    title: 'Storage Analyzer',
    description: 'See a breakdown of what is using your storage',
    icon: 'pie-chart',
    category: 'storage',
    route: '/tools/storage-overview',
  },
  {
    id: 'file-browser',
    title: 'File Browser',
    description: 'Browse, search and manage files on your device',
    icon: 'folder',
    category: 'browser',
    route: '/(tabs)/files',
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.id === id);
}
